name: print
on: push
env:
  continue: true
  time: 3
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix={'include':[{'project':'foo','config':'Debug'},{'project':'bar','config':'Release'}]}" >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: print details                       
        run: |
          echo ${{ fromJSON(needs.job1.outputs.matrix) }}
          echo ${{ toJSON(needs.job1.outputs.matrix) }}
          
      - name: run script                       
        run: python src/createTask.py --myArg1=${{ toJSON(needs.job1.outputs.matrix) }}
